"""autogenerated by genmsg_py from DIO.msg. Do not edit."""
import roslib.message
import struct


class DIO(roslib.message.Message):
  _md5sum = "d375575ab5b2233ab16927780da5f856"
  _type = "p2os_driver/DIO"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 count
uint16 bits

"""
  __slots__ = ['count','bits']
  _slot_types = ['uint32','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       count,bits
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(DIO, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.count is None:
        self.count = 0
      if self.bits is None:
        self.bits = 0
    else:
      self.count = 0
      self.bits = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_IH.pack(_x.count, _x.bits))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.count, _x.bits,) = _struct_IH.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_IH.pack(_x.count, _x.bits))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.count, _x.bits,) = _struct_IH.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_IH = struct.Struct("<IH")
